name: rbnc
version: 1.0.5
grade: stable
summary: Reverse-Beacon-Network Desktop-Client
description: |
  RBNC is a system tray client application to the reverse beacon network.

confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  kochmorse:
    command: kochmorse
    desktop: usr/share/applications/kochmorse.desktop
    plugs:
      - desktop
      - network
      - audio-playback

parts:
  kochmorse:
    plugin: cmake
    build-packages:
      - qtbase5-dev
      - qtmultimedia5-dev
      - qtpositioning5-dev
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - libqt5multimedia5
      - libqt5positioning5
      - libqt5multimedia5-plugins
    source: https://github.com/hmatuschek/skcc.git
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
